### ISSUE TITLE
Wrong version

### ISSUE THREAD

**Issue by FDiskas** [aabluedragon/vkbeautify#1]
You should follow the rules http://semver.org
`error "vkbeautify" is wrong version: expected "0.99.1", got "0.99.01"`

**Comment by aabluedragon** [comment]
Executed "npm i --save vkbeautify", no warning on output, package.json looks fine:
```
"dependencies": {
    "vkbeautify": "^0.99.1"
},
```
Output of `npm view vkbeautify`, also looks correct.

**Comment by FDiskas** [comment]
Check installed package.json version

**Comment by aabluedragon** [comment]
"0.99.1".
Feel free to submit a PR with your requested correction. 👍

**Comment by FDiskas** [comment]
Or download it directly https://registry.npmjs.org/vkbeautify/-/vkbeautify-0.99.1.tgz
` "version": "0.99.01",`
but https://www.npmjs.com/package/vkbeautify displays it as `v0.99.1`

**Comment by FDiskas** [comment]
But you should republish the package :fountain:
